### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by nieqqo** [AndydeCleyre/archbuilder_iosevka#2]
Oh, this is just horrible! It seems like in my life, things never quite go the way I want them to. But I'd love to learn how to use your customizer so that I could try again. I ended up not liking what I put together, so I'm hoping I can make it better!

I'm not a native English speaker, but I understand it well enough. However, when we start using some complicated terms, I get lost and don't understand anything. Could you please explain to me right from the beginning what I need to do? I mean, when you have already got the code with settings for customization.

**Comment by nieqqo** [comment]
I've forked the customizer, so now what?

**Comment by AndydeCleyre** [comment]
What OS are you using? Have you used a terminal before?

**Comment by nieqqo** [comment]
> What OS are you using? Have you used a terminal before?

I've got Windows 10 Pro, but it's not activated. I haven't actually used the terminal at all.

**Comment by AndydeCleyre** [comment]
OK, here's what I suggest:

- Install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), which will give you a mini Linux system to work in. The default flavor, Ubuntu, is fine.
- Set your name and email for git, by running these two commands in your WSL terminal, replacing the values with your own. The `$ ` at the beginning of each line is not for you to type, it's just a signal that you're a regular user and this is the prompt where you type.

```console
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"
```

- Create a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-personal-access-token-classic). Later when you push your changes, it will ask for a password, and this is it. There are other ways to authenticate that are easier in the long run, but this is probably the easiest to just get going with.
- Look back to the README and try to follow the steps. "\<your-github-fork>" will be "https://github.com/nieqqo/archbuilder_iosevka". When you need to replace and edit files, you should be able to open the folder with your usual file explorer by running:

```console
$ explorer.exe .
```

- In `vars.nt`, the lines which lead with spaces then `#` are the commented ones.

- Come back here with what you did and didn't get done, and we'll work from there.

**Comment by nieqqo** [comment]
> * Install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), which will give you a mini Linux system to work in. The default flavor, Ubuntu, is fine.

I'm already having some issues with this. Despite following the tutorial to the letter, I'm unable to complete the installation.

**Comment by nieqqo** [comment]
> > * Install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), which will give you a mini Linux system to work in. The default flavor, Ubuntu, is fine.
> 
> I'm already having some issues with this. Despite following the tutorial to the letter, I'm unable to complete the installation.

```
sudo : The name “sudo” is not recognized as the name of a cmdlet, function, script file or executable program. Check the spelling of the name and the presence and correctness of the path, then try again.
If the name is spelled correctly, and if the path is present and correct, then try again.
line:1 character:1
+ sudo apt install build-essential flex bison dwarves libssl-dev libelf ...
+ ~~~~
    + CategoryInfo : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
😭

**Comment by AndydeCleyre** [comment]
1. That linked page doesn't include any direction to use `sudo` or `apt`, so I don't know which directions you're following.
2. That looks like you are running Linux commands but in Windows Powershell, instead of the Linux system. Please check the header [Ways to run multiple Linux distributions with WSL](https://learn.microsoft.com/en-us/windows/wsl/install#ways-to-run-multiple-linux-distributions-with-wsl) on that page linked in your quote, where it says:

> There are several ways to run your Linux distributions once installed:

for ways to launch the WSL.

**Comment by nieqqo** [comment]
> 1. That linked page doesn't include any direction to use `sudo` or `apt`, so I don't know which directions you're following.
> 2. That looks like you are running Linux commands but in Windows Powershell, instead of the Linux system. Please check the header [Ways to run multiple Linux distributions with WSL](https://learn.microsoft.com/en-us/windows/wsl/install#ways-to-run-multiple-linux-distributions-with-wsl) on that page linked in your quote, where it says:
> 
> > There are several ways to run your Linux distributions once installed:
> 
> for ways to launch the WSL.

I've been trying to get this to work, but I'm having some issues. The installation seems to have stopped at 16% and nothing is happening. It's been like this for about 40 minutes.

**Comment by AndydeCleyre** [comment]
If you can't' get WSL working, you may have luck with [git bash](https://www.atlassian.com/git/tutorials/git-bash) instead. I don't know if it comes with Python out of the box, though.

**Comment by nieqqo** [comment]
> If you can't' get WSL working, you may have luck with [git bash](https://www.atlassian.com/git/tutorials/git-bash) instead. I don't know if it comes with Python out of the box, though.

I installed it!!

**Comment by nieqqo** [comment]
> I installed it!!

I'm trying to do
```
git clone <https://github.com/nieqqo/archbuilder_iosevka>
cd archbuilder_iosevka
```
but it's giving me
`bash: syntax error near unexpected token 'newline'`

**Comment by AndydeCleyre** [comment]
Don't use the angled brackets.

**Comment by nieqqo** [comment]
> Don't use the angled brackets.

I did it! What now?

**Comment by AndydeCleyre** [comment]
Go back to the README and try to follow the rest of the steps, with some additional tips in [this comment](https://github.com/AndydeCleyre/archbuilder_iosevka/issues/2#issuecomment-2417559546). Let me know which step gives you grief next.

**Comment by nieqqo** [comment]
> Go back to the README and try to follow the rest of the steps, with some additional tips in [this comment](https://github.com/AndydeCleyre/archbuilder_iosevka/issues/2#issuecomment-2417559546). Let me know which step gives you grief next.

`bash: vars.nt: command not found`
help?/?\😭

**Comment by AndydeCleyre** [comment]
That's a file name, and you should not try to run it as a command. If you are in the repo folder in git bash, try this and see if it shows you the files in your usual file explorer, so you can edit with your favorite editor.

```
explorer .
```

**Comment by nieqqo** [comment]
> That's a file name, and you should not try to run it as a command. If you are in the repo folder in git bash, try this and see if it shows you the files in your usual file explorer, so you can edit with your favorite editor.
> 
> ```
> explorer .
> ```

Yes! It worked!

**Comment by nieqqo** [comment]
> > That's a file name, and you should not try to run it as a command. If you are in the repo folder in git bash, try this and see if it shows you the files in your usual file explorer, so you can edit with your favorite editor.
> > ```
> > explorer .
> > ```
> 
> Yes! It worked!

what now??

**Comment by nieqqo** [comment]
> what now??

Do I need to install Python? Bcs it's telling me `Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90P` to `$ ./mk/buildpkg.yml.sh`

**Comment by nieqqo** [comment]
> > what now??
> 
> Do I need to install Python? Bcs it's telling me `Python was not found but can be installed from the Microsoft Store: ms-windows-store://pdp/?productid=9NJ46SX7X90P` to `$ ./mk/buildpkg.yml.sh`

i edited vars.nt
what next?

**Comment by AndydeCleyre** [comment]
You need to have Python, yes. I don't know the best way to install or invoke it in git bash for Windows, as I've never used it and don't have access to Windows.

**Comment by AndydeCleyre** [comment]
Sorry I don't have a Windows system to test things on. If you get WSL working it'll be simpler.

**Comment by nieqqo** [comment]
> Sorry I don't have a Windows system to test things on. If you get WSL working it'll be simpler.

This is taking a long time. I actually installed Windows Terminal and am now installing Ubuntu because I need a Linux distribution.

**Comment by nieqqo** [comment]
I also want to thank you for all your help so far, even though we haven't finished yet. I just wanted to say thanks for spending your time helping me out over the last 3 or 4 days.

**Comment by nieqqo** [comment]
Hi! It's been five days since my last appearance. I'm having a bit of trouble replacing Git Bash with Windows Terminal. Some of the things I was doing stopped working, etc.

I'm really sorry for taking up so much of your time, but I'm afraid I don't understand anything. I thought I didn't need it as much anymore. Thank you so much again!!
